#!/usr/bin/env python3
"""Generate compile_commands.json so CLion can index this repo without a
cross-toolchain or a real CMake configure. Read-only aid: nothing here is used
by an actual build. Re-run after changing the file list.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SDK = ROOT / "lib" / "pico-sdk"
STUBS = ROOT / ".clion-index"

inc = [STUBS, ROOT / "include", ROOT / "include" / "boards"]
for base in ("src/common", "src/rp2_common", "src/rp2350"):
    inc += sorted((SDK / base).glob("*/include"))
inc.append(SDK / "src" / "boards" / "include")

defines = [
    "PICO_NO_HARDWARE=0", "PICO_ON_DEVICE=1", "PICO_BUILD=1",
    "PICO_RP2350=1", "PICO_32BIT=1", "PICO2_ICE",
]

# Out of scope per CLAUDE.md: USB drag-and-drop / DFU loading.
sources = [
    p for p in sorted((ROOT / "src").glob("*.c"))
    if p.name != "ice_usb.c" and not p.name.startswith("tinyuf2_")
]
# Examples that cannot be indexed without an actual build:
#   bitstream.h  - generated by yosys/nextpnr/icepack + bin2header.py
#                  (e.g. examples/rp2_ice_blinky/CMakeLists.txt:32-37)
#   tusb.h       - needs pico-sdk's own lib/tinyusb submodule, not checked out
#   ice_spi.h    - does not exist anywhere in this repo at f3ddedc; upstream
#                  examples/rp2_fpga_io/main.c:29 and rp2_usb_spi/main.c:38
#                  still include it
SKIP_EXAMPLES = {
    "rp2_ice_blinky", "rp2_ice_i2c", "rp2_ice_i2c_7seg",   # bitstream.h
    "rp2_flash_repl", "rp2_hello_world",                   # tusb.h
    "rp2_fpga_io",                                         # ice_spi.h
}
sources += [
    p for p in sorted((ROOT / "examples").glob("*/main.c"))
    if not p.parent.name.startswith("rp2_usb")
    and p.parent.name not in SKIP_EXAMPLES
]

flags = ["cc", "-std=gnu11", "-fsyntax-only"]
flags += ["-include", str(STUBS / "host_compat.h")]
flags += [f"-D{d}" for d in defines]
flags += [f"-I{d}" for d in inc]

db = [
    {"directory": str(ROOT), "arguments": flags + [str(s)], "file": str(s)}
    for s in sources
]
(ROOT / "compile_commands.json").write_text(json.dumps(db, indent=1) + "\n")
print(f"{len(db)} entries, {len(inc)} include dirs")
