#!/usr/bin/env python3
"""Generate compile_commands.json so CLion can index this repo without a
cross-toolchain or a real CMake configure. Read-only aid: nothing here is used
by an actual build. Re-run after changing the file list.

    python3 .clion-index/gen_compile_commands.py            generate
    python3 .clion-index/gen_compile_commands.py --check     generate, then
                                                            compile every entry

--check is the only honest test that indexing works. CLion going quiet is not:
a file that fails to parse produces no warning, it just silently stops
resolving its own symbols. Run it on any new machine, and whenever the host
compiler or libc changes.

The host compiler stands in for arm-none-eabi-gcc, so $CC can be anything that
parses GNU C. Verified with gcc 16 / glibc; Apple clang with the Darwin SDK is
expected to work because host_compat.h only fills gaps it finds (see the
#ifndef guards there), but it is untested.
"""
import json
import os
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SDK = ROOT / "lib" / "pico-sdk"
STUBS = ROOT / ".clion-index"
CC = os.environ.get("CC", "cc")

if not (SDK / "src" / "rp2350").is_dir():
    sys.exit("lib/pico-sdk is empty. Run:\n"
             "    git submodule update --init lib/pico-sdk")

inc = [STUBS, ROOT / "include", ROOT / "include" / "boards"]
for base in ("src/common", "src/rp2_common", "src/rp2350"):
    inc += sorted((SDK / base).glob("*/include"))
inc.append(SDK / "src" / "boards" / "include")

defines = [
    "PICO_NO_HARDWARE=0", "PICO_ON_DEVICE=1", "PICO_BUILD=1",
    "PICO_RP2350=1", "PICO_32BIT=1", "PICO2_ICE",
]

# Out of scope per CLAUDE.md: USB drag-and-drop / DFU loading.
sources = [
    p for p in sorted((ROOT / "src").glob("*.c"))
    if p.name != "ice_usb.c" and not p.name.startswith("tinyuf2_")
]
# Examples that cannot be indexed without an actual build:
#   bitstream.h  - generated by yosys/nextpnr/icepack + bin2header.py
#                  (e.g. examples/rp2_ice_blinky/CMakeLists.txt:32-37)
#   tusb.h       - needs pico-sdk's own lib/tinyusb submodule, not checked out
#   ice_spi.h    - does not exist anywhere in this repo at f3ddedc; upstream
#                  examples/rp2_fpga_io/main.c:29 and rp2_usb_spi/main.c:38
#                  still include it
SKIP_EXAMPLES = {
    "rp2_ice_blinky", "rp2_ice_i2c", "rp2_ice_i2c_7seg",   # bitstream.h
    "rp2_flash_repl", "rp2_hello_world",                   # tusb.h
    "rp2_fpga_io",                                         # ice_spi.h
}
sources += [
    p for p in sorted((ROOT / "examples").glob("*/main.c"))
    if not p.parent.name.startswith("rp2_usb")
    and p.parent.name not in SKIP_EXAMPLES
]

flags = [CC, "-std=gnu11", "-fsyntax-only"]
flags += ["-include", str(STUBS / "host_compat.h")]
flags += [f"-D{d}" for d in defines]
flags += [f"-I{d}" for d in inc]

db = [
    {"directory": str(ROOT), "arguments": flags + [str(s)], "file": str(s)}
    for s in sources
]
(ROOT / "compile_commands.json").write_text(json.dumps(db, indent=1) + "\n")
print(f"{len(db)} entries, {len(inc)} include dirs, CC={CC}")

if "--check" not in sys.argv:
    sys.exit(0)

failed = 0
for entry in db:
    name = str(pathlib.Path(entry["file"]).relative_to(ROOT))
    proc = subprocess.run(entry["arguments"], cwd=entry["directory"],
                          capture_output=True, text=True)
    errors = [ln for ln in proc.stderr.splitlines() if "error:" in ln]
    if errors:
        failed += 1
        print(f"FAIL {name}\n     {errors[0]}")
    else:
        print(f"ok   {name}")

print(f"\n{len(db) - failed}/{len(db)} parse clean")
if failed:
    print("A new host compiler or libc may need another #ifndef block in "
          "host_compat.h; see the __unused / __CONCAT entries there.")
sys.exit(1 if failed else 0)
